// Generated by CoffeeScript 1.3.3
var OkApi, md5, requestOptions, rest, sys, _, _callback;

sys = require('util');

rest = require('restler');

_ = require('underscore');

md5 = require("blueimp-md5").md5;

requestOptions = {
  applicationSecretKey: null,
  applicationKey: null,
  applicationId: null,
  accessToken: null,
  refreshToken: null,
  restBase: 'http://api.odnoklassniki.ru/fb.do',
  refreshBase: 'http://api.odnoklassniki.ru/oauth/token.do'
};

exports.version = '1.0.0';

OkApi = (function() {
  var makeRequest, okSignature, parametrize, validateOptions;

  function OkApi(method, postData, callback) {
    validateOptions();
    makeRequest(method, postData, callback);
  }

  makeRequest = function(method, postData, callback) {
    var error, getUrl, requestedData;
    requestedData = {
      access_token: requestOptions['accessToken'],
      application_key: requestOptions['applicationKey'],
      sig: okSignature(postData)
    };
    _.extend(requestedData, postData);
    error = null;
    switch (method) {
      case 'POST':
        return rest.post(requestOptions['restBase'], {
          data: requestedData
        }).on('complete', function(data, response) {
          return _callback(data, response, callback);
        });
      case 'GET':
        getUrl = ("" + requestOptions['restBase'] + "?") + parametrize(requestedData, '&');
        return rest.get(getUrl).on('complete', function(data, response) {
          return _callback(data, response, callback);
        });
      default:
        throw 'HTTP verb not supported';
    }
  };

  okSignature = function(postData) {
    var hashStr, secret, sortedParams;
    postData['application_key'] = requestOptions['applicationKey'];
    sortedParams = parametrize(postData);
    hashStr = "" + requestOptions['accessToken'] + requestOptions['applicationSecretKey'];
    secret = md5(hashStr);
    return md5("" + sortedParams + secret);
  };

  parametrize = function(obj, join) {
    var arrayOfArrays, sortedParams, symbol;
    if (join == null) {
      join = false;
    }
    arrayOfArrays = _.pairs(obj).sort();
    symbol = join ? '&' : '';
    sortedParams = '';
    _.each(arrayOfArrays, function(value) {
      return sortedParams += ("" + (_.first(value)) + "=" + (_.last(value))) + symbol;
    });
    return sortedParams;
  };

  validateOptions = function() {
    if (!((requestOptions['applicationKey'] != null) || (requestOptions['applicationId'] != null) || (requestOptions['applicationSecretKey'] != null))) {
      throw 'Please setup requestOptions with valid params. @see https://github.com/astronz/ok.ru';
    }
    if (requestOptions['accessToken'] == null) {
      throw 'AccessToken does not initialized. @see https://github.com/astronz/ok.ru';
    }
  };

  return OkApi;

})();

exports.api = OkApi;

_callback = function(data, response, callback) {
  var error;
  if (data instanceof Error) {
    return callback(data.message, data, response);
  } else {
    if (data.hasOwnProperty('error_code')) {
      error = data;
    }
    return callback(error, data, response);
  }
};

exports.refresh = function(refreshToken, callback) {
  var refresh_params;
  if (refreshToken == null) {
    refreshToken = '';
  }
  if (refreshToken != null) {
    requestOptions['refreshToken'] = refreshToken;
  }
  if (requestOptions['refreshToken'] == null) {
    throw 'RefreshToken does not set. @see https://github.com/astronz/ok.ru';
  }
  refresh_params = {
    refresh_token: requestOptions['refreshToken'],
    grant_type: 'refresh_token',
    client_id: requestOptions['applicationId'],
    client_secret: requestOptions['applicationSecretKey']
  };
  return rest.post(requestOptions['refreshBase'], {
    data: refresh_params
  }).on('complete', function(data, response) {
    return _callback(data, response, callback);
  });
};

exports.post = function(params, callback) {
  return new OkApi('POST', params, callback);
};

exports.get = function(params, callback) {
  return new OkApi('GET', params, callback);
};

exports.setAccessToken = function(token) {
  return _.extend(requestOptions, {
    accessToken: token
  });
};

exports.getAccessToken = function() {
  return requestOptions['accessToken'];
};

exports.setOptions = function(options) {
  if (typeof options === 'object') {
    return _.extend(requestOptions, options);
  }
};

exports.getOptions = function() {
  return requestOptions;
};
